name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.304'   # Use your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish Windows EXE
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true

      - name: Copy published windows files to win64 directory
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path win64

          # Find all publish directories
          $publishDirs = Get-ChildItem -Path ./bin/Release/net9.0/win-x64 -Recurse -Directory -Filter publish

          foreach ($dir in $publishDirs) {
            # Copy all .exe files
            Copy-Item -Path "$($dir.FullName)\*.exe" -Destination artifact -Force -ErrorAction Ignore

            # Copy all .dll files
            Copy-Item -Path "$($dir.FullName)\*.dll" -Destination artifact -Force -ErrorAction Ignore

            # Copy shader folder if it exists
            if (Test-Path "$($dir.FullName)\shader") {
              Copy-Item -Path "$($dir.FullName)\shader" -Destination win64 -Recurse -Force
            }
          }

      - name: Upload win64
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_number }} win64
          path: win64/**

      - name: Zip the win64 directory
        shell: pwsh
        run: Compress-Archive -Path win64/* -DestinationPath win64.zip


      - name: Publish MacOS
        run: dotnet publish -c Release -r osx-x64 --self-contained true -p:PublishSingleFile=true

      - name: Copy published windows files to osx64 directory
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path osx64

          # Find all publish directories
          $publishDirs = Get-ChildItem -Path ./bin/Release/net9.0/osx-x64 -Recurse -Directory -Filter publish

          foreach ($dir in $publishDirs) {
            # Copy all files
            Copy-Item -Path "$($dir.FullName)\*" -Destination osx64 -Force -ErrorAction Ignore

            # Copy shader folder if it exists
            if (Test-Path "$($dir.FullName)\shader") {
              Copy-Item -Path "$($dir.FullName)\shader" -Destination osx64 -Recurse -Force
            }
          }

      - name: Upload osx64
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.run_number }} osx64
          path: osx64/**

      - name: Zip the osx64 directory
        shell: pwsh
        run: Compress-Archive -Path osx64/* -DestinationPath osx64.zip


      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Automated build.
            - Build version: v1.${{ github.run_number }}

            Download the .zip file corresponding to your os.
            ex. win64 for Windows, osx64 for MacOS.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Windows Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: win64.zip
          tag_name: ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MacOS Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: osx64.zip
          tag_name: ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}