name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.304'   # Use your .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Publish EXE
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable
          path: |
            **/bin/Release/net*/win-x64/publish/*.exe
            **/bin/Release/net*/win-x64/publish/*.dll